FROM quay.io/fedora/fedora-bootc:43

RUN systemctl disable bootc-fetch-apply-updates.timer && \
    systemctl disable sshd && \
    mkdir -p -m 0700 /var/roothome && \
    echo "fedora" > /etc/hostname

RUN dnf install -y @xfce-desktop-environment && \
    dnf install -y lightdm firefox libreoffice labwc wlroots flatpak gimp && \
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo && \
    flatpak install -y --noninteractive flathub com.vscodium.codium && \
    systemctl enable lightdm --force && \
    systemctl set-default graphical.target && \
    dnf clean all && \
    rm -fr /var/log/*.log && \
    rm -fr /var/log/*.log.*

RUN bootc container lint