FROM quay.io/fedora/fedora-bootc:42

RUN mkdir -p /var/roothome

RUN echo "fedora" > /etc/hostname

RUN dnf install -y @xfce-desktop-environment && \
    dnf install -y lightdm firefox libreoffice labwc wlroots flatpak gimp && \
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo && \
    flatpak install -y --noninteractive flathub com.vscodium.codium && \
    systemctl enable lightdm --force && \
    systemctl set-default graphical.target && \
    systemctl disable sshd && \
    dnf clean all

RUN bootc container lint