FROM quay.io/fedora/fedora-bootc:43

COPY flatpaks-install.sh /usr/local/bin/flatpaks-install.sh
COPY flatpaks-update.sh /usr/local/bin/flatpaks-update.sh
COPY firstboot.service /etc/systemd/system/firstboot.service
COPY atboot.service /etc/systemd/system/atboot.service

RUN systemctl disable bootc-fetch-apply-updates.timer && \
    systemctl disable sshd && \
    chmod +x /usr/local/bin/flatpaks-update.sh && \
    chmod +x /usr/local/bin/flatpaks-install.sh && \
    systemctl enable firstboot.service && \
    systemctl enable atboot.service && \
    mkdir -p -m 0700 /var/roothome && \
    echo "fedora" > /etc/hostname

RUN dnf group install -y gnome-desktop && \
    dnf install -y fedora-release-ostree-desktop gnome-shell-extension-dash-to-dock wget && \
    dnf remove -y gnome-initial-setup gnome-tour decibels showtime simple-scan snapshot && \
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo && \
    systemctl set-default graphical.target && \
    dnf clean all && \
    rm -fr /var/cache/* && \
    rm -fr /var/lib/dnf/repos/* && \
    rm -fr /var/lib/flatpak/repo/tmp/cache/* && \
    rm -fr /var/log/*.log && \
    rm -fr /var/log/*.log.*

RUN systemctl --global mask packagekit.service && \
    echo -e '[org/gnome/settings-daemon/plugins/housekeeping]\ndonation-reminder-enabled="false"' > /etc/dconf/db/local.d/01-housekeeping && \
    echo -e '[org/gnome/software]\ndownload-updates="false"\nallow-uninstall="false"\nfirst-run="false"' > /etc/dconf/db/local.d/02-software && \
    echo -e '[org/gnome/shell]\nenabled-extensions=["dash-to-dock@micxgx.gmail.com"]' > /etc/dconf/db/local.d/03-shell && \
    dconf update

RUN bootc container lint